import { useState } from "react";
import { useAuth } from "../AuthContext";
import {
  ChevronDown, ChevronUp, Search, BookOpen, LayoutDashboard, Megaphone,
  Calendar, Layers, GraduationCap, Users, UserPlus, Package, Quote,
  Mail, ShieldCheck, Settings, ClipboardList, FileText, Newspaper,
  HelpCircle, Lock, Globe, Sparkles,
  Building2, Server, Database, Code2, GitBranch, Shield,
  Cpu, RefreshCw, KeyRound, Network, BarChart2, Wrench,
} from "lucide-react";

// ─── Types ────────────────────────────────────────────────────────────────────

type Role = "admin" | "teacher" | "assistant" | "all";

type SpecSection = {
  id: string;
  title: string;
  icon: React.ElementType;
  roles: Role[];
  color: string;
  overview: string;
  steps?: { heading: string; detail: string }[];
  tips?: string[];
  notes?: string[];
};

// ─── Specification data ───────────────────────────────────────────────────────

const SECTIONS: SpecSection[] = [
  {
    id: "auth",
    title: "Login & Authentication",
    icon: Lock,
    roles: ["all"],
    color: "from-slate-500 to-slate-700",
    overview:
      "The portal supports two login methods: email + password for Super Admin, and phone number + 4-digit PIN for teachers and assistants. PINs are auto-generated when a staff member is added in Staff Management. Accounts lock after 5 consecutive wrong PIN entries for 15 minutes.",
    steps: [
      { heading: "Super Admin login", detail: "Navigate to /admin/login. Enter your registered email address and password, then click Sign In." },
      { heading: "Teacher / Assistant login", detail: "On the login page, type your 10-digit phone number (digits only). The form switches to PIN mode automatically. Enter your 4-digit PIN and click Sign In." },
      { heading: "How teachers get their PIN", detail: "PINs are auto-generated by the system when the Admin adds a staff member in Staff Management. The PIN appears once in a green banner — the Admin must copy it and share it securely. After the banner is dismissed, the PIN cannot be retrieved (only reset)." },
      { heading: "Forgot PIN / Reset PIN", detail: "Ask the Admin to click the 🔑 Reset PIN button next to your name in Staff Management. A new PIN will be generated and shown in the banner." },
      { heading: "Change credentials", detail: "Admins change their password from Settings → Change Password. Teachers change their PIN from Settings → Change PIN." },
    ],
    tips: [
      "PINs are 4 numeric digits — do not share them with others.",
      "After 5 wrong PIN attempts the account is locked for 15 minutes automatically.",
      "The login form detects phone vs email input automatically and switches mode.",
      "PINs are bcrypt-hashed in the database — nobody, including admins, can read them after creation.",
    ],
  },
  {
    id: "dashboard",
    title: "Dashboard",
    icon: LayoutDashboard,
    roles: ["admin"],
    color: "from-indigo-500 to-indigo-700",
    overview:
      "The Dashboard is the Admin's home screen, providing a high-level snapshot of the Gurukul's operations — student counts, teacher counts, upcoming events, and recent announcements.",
    steps: [
      { heading: "Access", detail: "Admins are redirected here automatically after login. Teachers and Assistants see Courses & Classes instead." },
      { heading: "Stats cards", detail: "Top cards show total students, active teachers, upcoming events, and today's attendance rate." },
      { heading: "Recent activity", detail: "Scroll down to see the latest announcements and any recently published weekly updates." },
    ],
    tips: ["The Dashboard is a read-only summary — no edits happen here. Use the sidebar links to manage each area."],
  },
  {
    id: "members",
    title: "Member Management",
    icon: Building2,
    roles: ["admin"],
    color: "from-sky-500 to-sky-700",
    overview:
      "Member Management handles the temple membership records that every Gurukul student must be linked to. A student cannot be registered without selecting an active temple member. Memberships expire on December 31 of the registration or renewal year and must be renewed each calendar year. Membership status is automatically calculated: Active (current year), Expiring Soon (within 30 days of December 31), or Expired. The summary tiles at the top include Validated and Invalidated counts that act as one-click filters.",
    steps: [
      { heading: "View members", detail: "Go to Member Management. The page loads all members at once with live client-side filtering. Stats tiles at the top show: Total Members, Active, Expired, With Students, Added this month, Validated, and Invalidated." },
      { heading: "Use summary tiles as filters", detail: "Click the green Validated tile to instantly filter the list to only verified members. Click the red Invalidated tile to show members whose identity check failed. Click the tile again to clear the filter. An active tile shows a coloured ring." },
      { heading: "Filter members", detail: "Use the Status pill buttons (All / Active / Expiring Soon / Expired) to filter by membership health. Use the Students pill buttons to find members with or without enrolled children. Use the Verification filter (Verified / Not Verified / Overdue) to filter by validation status." },
      { heading: "Sort", detail: "Click column headers (ID, Name, Email, Join Date, Verification) to sort. Sorting by Verification surfaces overdue members first, then invalidated, then verified last." },
      { heading: "Add a member", detail: "Click Add Member. Enter name, email, phone (all three mandatory), and optionally a membership year and employer. Click Save — the member is created immediately and can now be linked to students." },
      { heading: "View member detail", detail: "Click the eye (👁) icon on any member row to open a detail panel. The panel shows all member info, membership status, validation status with the verifying admin's name and date, and a list of all linked students." },
      { heading: "Edit a member", detail: "Click the pencil (✏) icon to update name, email, phone, employer, or membership year." },
      { heading: "Delete a member", detail: "Click the trash (🗑) icon. Deletion is blocked if the member has students linked — remove or re-link those students first." },
      { heading: "Export", detail: "Click Download CSV to export all filtered members. The CSV includes a Validation Status column showing Verified, Not Verified, or overdue status with days." },
    ],
    notes: [
      "Every Gurukul student must be linked to a temple member — memberId is mandatory at registration.",
      "Only members with Active status can have new students registered against them.",
      "The Verified badge in the member table shows the name of the admin who verified it and the date — visible below the badge in the Verification column.",
      "Members cannot be deleted while they have students linked to them.",
    ],
    tips: [
      "Check 'Expiring Soon' regularly and remind families to renew their temple membership before it lapses.",
      "Use the Invalidated tile to quickly surface members who failed identity verification and need follow-up.",
      "Use the 'Without Students' filter to find temple members who have not yet enrolled any children — a useful outreach list.",
    ],
  },
  {
    id: "member-validation",
    title: "Member Identity Validation",
    icon: ShieldCheck,
    roles: ["admin"],
    color: "from-emerald-500 to-emerald-700",
    overview:
      "Member Validation is the identity verification workflow for temple members. Admins verify a member's identity in person by checking a government-issued ID card, then recording the verification in the portal. Validated members show a green Verified badge; invalidated members show a red badge. Members who have been registered for more than 90 days without verification are flagged as Overdue with an orange badge.",
    steps: [
      { heading: "Open the validation form", detail: "Click the green Verify button on any member's detail panel, or click the shield icon on the member row in the table. The Validate Member modal opens." },
      { heading: "Select ID type", detail: "Choose the ID document the member presented: State ID, Driver's License, Passport, or Other." },
      { heading: "Enter last 4 digits", detail: "Record the last 4 digits of the ID number for audit purposes." },
      { heading: "Enter issuing authority", detail: "Enter the state or country that issued the document (e.g. Ohio, India)." },
      { heading: "Choose outcome", detail: "Select Validated (identity confirmed) or Invalidated (document could not be verified or was rejected). Add optional notes for context." },
      { heading: "Save", detail: "Click Save. The member's Validation Badge updates immediately. The portal records the admin's name, date, and all ID details in the member record." },
      { heading: "Overdue banner", detail: "A yellow banner appears at the top of the Member Management page if any members have been registered for more than 90 days without validation. Click 'Show Overdue' in the banner to filter directly to those members." },
    ],
    notes: [
      "Validation is recorded permanently: the admin name, date, ID type, last 4 digits, and notes are stored on the member record.",
      "A member can be re-validated at any time — the latest validation overwrites the previous one.",
      "Invalidated members are still linked to their students — invalidation does not block access or remove enrollments.",
      "The Verified badge in the member table shows the verifying admin's name and date beneath the badge text.",
    ],
    tips: [
      "Use the Validation filter in the Filters panel to show only Overdue members and batch-verify them during a temple event.",
      "Add a note when invalidating so future admins know the reason (e.g. 'ID expired', 'name mismatch').",
      "The Validated and Invalidated summary tiles on the Member Management page are clickable — use them to quickly jump to filtered views.",
    ],
  },
  {
    id: "registration",
    title: "Student Registration",
    icon: UserPlus,
    roles: ["admin"],
    color: "from-emerald-500 to-emerald-700",
    overview:
      "Student Registration is the form used to admit new students into the Gurukul and enrol them in a course section. Every student must be linked to an active temple member record (the member represents the family). Once registered, the student is visible in Student Management and appears in the teacher's attendance roster.",
    steps: [
      { heading: "Open the form", detail: "Go to Student Registration in the sidebar, or click the + Register Student button from the Student Management page. The form opens as a slide-over panel." },
      { heading: "Link to a temple member (mandatory)", detail: "Start typing the family's name or phone in the Member search box. Select the matching active member from the dropdown. This links the student to the family's temple membership. Only Active members appear — Expired memberships must be renewed first." },
      { heading: "Enter student details", detail: "Fill in: Student Name, Date of Birth, Grade (school grade level), Curriculum Year, and check 'New Student' if this is their first year at the Gurukul." },
      { heading: "Enter parent contacts", detail: "Fill in mother and father details separately — each has their own Name, Phone, and Email fields. Both sets are optional but at least one contact is strongly recommended for communication purposes." },
      { heading: "Choose enrollment", detail: "Select Course → Level → Section using the cascading dropdowns. The section automatically determines the assigned teacher. You can leave section blank if class placement is still pending." },
      { heading: "Set payment details", detail: "Enter the fee Amount Due, Amount Paid (0 if not yet paid), Payment Method (Cash / Check / Online / Waived), and an optional Receipt ID." },
      { heading: "Submit", detail: "Click Register Student. The student immediately appears in Student Management and in the teacher's class roster for attendance." },
    ],
    notes: [
      "A temple member link (memberId) is required — you cannot save a registration without selecting a member.",
      "Only members with Active membership status can be selected. Expired members are excluded from search results.",
      "A single member (family) can have multiple students registered under them.",
    ],
    tips: [
      "Register the temple membership first (in Member Management) before trying to register a student.",
      "Double-check phone numbers — parents use their phone number to verify identity on the Parent Portal.",
      "You can register a student without a section if class placement is still being decided — just update their enrollment later from Student Management.",
    ],
  },
  {
    id: "students",
    title: "Student Management",
    icon: Users,
    roles: ["admin"],
    color: "from-green-500 to-green-700",
    overview:
      "Student Management gives the Admin a complete view of all enrolled students across courses, with their parent contacts, payment status, and enrollment details. You can filter, sort, bulk-manage, view payment breakdowns, and export student data from this page.",
    steps: [
      { heading: "View students", detail: "The page loads all students at once. The table shows: Student Code, Name, Grade, Course, Level, Section, Parent Contact (M/F rows), Payment summary, Active status, and actions." },
      { heading: "Filter", detail: "Use the filter panel (funnel icon) to narrow by: Course, Level, Section, Payment Status (Paid/Pending/Overdue), Active Status (Active/Inactive), and Curriculum Year." },
      { heading: "Sort", detail: "Click any sortable column header — ID, Name, Grade, Course, Level, Payment Status, Total Paid, or Active — to sort ascending/descending." },
      { heading: "Parent Contact column", detail: "The Parent Contact column shows two rows per student: M (mother, in pink) with phone and email, and F (father, in blue) with phone and email. If a parent's contact is missing, that row is hidden." },
      { heading: "View payment details", detail: "Click anywhere on a student's Payment cell to open the Payment Details slide-over. It shows a card per enrollment with: Course, Level, Section, Timing, Payment Status badge, Amount Due / Paid / Balance boxes, Payment Method, Receipt #, and Enrollment Date. The footer shows the total Due, Paid, and Balance across all enrollments." },
      { heading: "Edit / record a payment", detail: "Inside the Payment Details slide-over, click 'Edit Payment' on any enrollment card to expand an inline form. You can update: Amount Due, Amount Paid, Payment Status (Paid / Pending / Overdue), Payment Method (Cash / Check / Zelle / Online / Waived), Receipt or Transaction #, and Payment Date. Click 'Save Payment' to commit — the drawer refreshes immediately and the student list updates in the background. Every payment edit is recorded in the audit log." },
      { heading: "Edit a student", detail: "Click the pencil (✏) icon to open the Edit Student panel. Update personal info, parent contacts, and enrollment course/level/section details." },
      { heading: "Mark active / inactive", detail: "Click the UserX / UserCheck icon on a student row to toggle their active status individually. Inactive students appear dimmed in all views." },
      { heading: "Bulk actions", detail: "Check the box on multiple student rows (or check the header to select all on the current page). Use the bulk action bar that appears to: Mark Active, Mark Inactive, or Delete selected students." },
      { heading: "Export", detail: "Click the Download CSV icon to export all currently-filtered students to a CSV file with all columns including parent contacts." },
      { heading: "Search", detail: "Type in the search box to instantly filter students by name or student code." },
    ],
    notes: [
      "Every student is linked to a temple member — the member link is permanent after registration and can only be changed by editing the student.",
      "Deleting a student permanently removes all their enrollments, attendance records, and payment history. This cannot be undone.",
      "Inactive students remain in the system and in all historical records — they are just hidden from active views.",
      "Online registration payments (Stripe) do NOT automatically update the admin payment records — admins must manually record any payment received via the Payment Details slide-over. The public registration form is for intent only; actual payment confirmation and DB update is always done by an admin.",
    ],
    tips: [
      "Use the Payment cell click to quickly check a family's balance without leaving the student list.",
      "The Payment column is sortable — sort by 'Payment Status' to surface all Overdue students at once.",
      "After recording an in-person payment (Cash / Check / Zelle), set Status to 'Paid', enter the method, and add a receipt number for a clean audit trail.",
      "Bulk-select Inactive students and use 'Mark Active' to re-enroll returning students at the start of a new year.",
      "The CSV export respects your current filters — filter first to export a specific class or payment group.",
    ],
  },
  {
    id: "course-management",
    title: "Course Management",
    icon: Layers,
    roles: ["admin"],
    color: "from-violet-500 to-violet-700",
    overview:
      "Course Management is where the Admin builds the complete class structure. The hierarchy is: Course → Level → Section. Everything else (teachers, students, attendance, weekly updates) is tied to this structure.",
    steps: [
      { heading: "Create a Course", detail: "Go to Course Management. Click Add Course. Enter the course name (e.g. Hindi, Sanskrit, Dharma, Telugu, Gujarati) and save." },
      { heading: "Add Levels", detail: "Under each course, add levels such as Beginner, Intermediate, Advanced, or Level 1, Level 2, etc. Levels represent the progression within a course." },
      { heading: "Add Sections", detail: "Under each level, add sections — these are the actual class batches (e.g. Section A on Saturdays 10 AM, Section B on Sundays 2 PM). Each section has its own enrolled students and assigned teacher." },
      { heading: "Edit or Archive", detail: "You can rename courses, levels, and sections at any time. Deleting a section will remove its attendance records, so archive rather than delete when possible." },
    ],
    tips: [
      "Plan your structure before adding teachers and students — changes later can be disruptive.",
      "Sections are the smallest unit — each has one teacher and one group of students.",
      "You can have multiple sections under the same level for different time slots.",
    ],
  },
  {
    id: "teachers",
    title: "Staff Management",
    icon: GraduationCap,
    roles: ["admin"],
    color: "from-blue-500 to-blue-700",
    overview:
      "Staff Management is where you add, edit, and assign teachers and teaching assistants. Adding a staff member automatically creates their portal login account and generates a secure 4-digit PIN. The Staff Schedule view shows every teacher's class assignments in a printable Course × Time-slot grid.",
    steps: [
      { heading: "Add a teacher", detail: "Click Add Teacher. Enter name, email, phone number, and choose category: Senior Teacher or Assistant. Optionally assign them to a course. Click Save — a portal account and PIN are created automatically." },
      { heading: "Share the PIN", detail: "After saving, a green banner appears at the top of the page showing the new teacher's phone number and generated PIN. Copy the PIN immediately and share it securely with the teacher. The banner disappears when dismissed — the PIN cannot be retrieved after that." },
      { heading: "Reset PIN", detail: "Click the 🔑 Reset PIN button on the teacher's row. A new PIN is generated instantly and shown in the banner. The old PIN is immediately invalidated." },
      { heading: "Edit assignment", detail: "Click the edit (pencil) icon to change a teacher's name, email, phone, or course assignment." },
      { heading: "Delete a teacher", detail: "Click the trash icon. This removes the teacher from Staff Management and also deletes their portal login account — they will no longer be able to log in." },
      { heading: "View Staff Schedule", detail: "Click the 'Staff Schedule' tab at the top of the Staff Management page. The schedule opens as a Course × Time-slot table: rows are courses, columns are time slots. Each filled cell shows the section and teacher name. Hover over any cell for a tooltip with full details (course, section, level, teacher, time)." },
      { heading: "Print Schedule", detail: "Click the Print button (top-right of the Schedule tab). A print-optimised popup opens with the same Course × Time grid formatted for A4/letter — use your browser's Print dialog to print or save as PDF." },
      { heading: "Day filter on Schedule", detail: "Click a day tab (Mon, Tue, … Sun) above the schedule grid to filter columns to only that day's time slots. This is useful when planning a specific day's staffing." },
    ],
    tips: [
      "The PIN banner disappears when you dismiss it — always copy it before dismissing.",
      "Resetting a PIN immediately invalidates the old one — the teacher will be logged out on their next request.",
      "Category 'Senior Teacher' maps to the 'teacher' portal role; 'Assistant' maps to the 'assistant' role.",
      "Use the Staff Schedule tab before making new assignments to spot any time conflicts.",
      "The printed schedule is useful to post in the classroom or share with coordinators.",
    ],
  },
  {
    id: "inventory",
    title: "Inventory",
    icon: Package,
    roles: ["admin"],
    color: "from-orange-500 to-orange-700",
    overview:
      "The Inventory module helps track physical assets and supplies owned or used by the Gurukul — textbooks, stationery, equipment, ceremonial items, and more.",
    steps: [
      { heading: "Add item", detail: "Click Add Item. Enter the item name, category, current quantity, and any notes." },
      { heading: "Update quantity", detail: "Click the edit icon on an item to adjust the quantity as items are used, restocked, or lost." },
      { heading: "Delete item", detail: "Remove items that are no longer tracked. This is permanent." },
      { heading: "Search", detail: "Use the search bar to quickly find items by name or category." },
    ],
    tips: ["Use categories consistently (e.g. Books, Stationery, Equipment) to make filtering easier.", "Consider adding a note when adjusting quantity to track why the change was made."],
  },
  {
    id: "testimonials",
    title: "Testimonials",
    icon: Quote,
    roles: ["admin"],
    color: "from-pink-500 to-pink-700",
    overview:
      "Testimonials are quotes from parents and students displayed on the public website's homepage and about page. They build trust with prospective families considering enrolment.",
    steps: [
      { heading: "Add testimonial", detail: "Click Add Testimonial. Enter the person's name, their relationship (Parent/Student/Alumni), and their quote." },
      { heading: "Publish / Draft", detail: "Set status to Published to display it on the website. Drafts are saved but not shown." },
      { heading: "Edit or Hide", detail: "Click edit to update the text. Set to Draft to hide without deleting." },
    ],
    tips: ["Keep quotes concise — 2–4 sentences is ideal for readability.", "Use real names (with consent) for authenticity."],
  },
  {
    id: "announcements",
    title: "Announcements",
    icon: Megaphone,
    roles: ["admin"],
    color: "from-rose-500 to-rose-700",
    overview:
      "Announcements are public notices posted on the Gurukul's website, visible to all visitors. Use them for important dates, closures, event notices, or any news you want to share broadly.",
    steps: [
      { heading: "Create", detail: "Click New Announcement. Enter a title, body text, and an optional expiry date. Set status to Published to show it on the website immediately." },
      { heading: "Draft vs Published", detail: "Drafts are saved but not visible publicly. You can edit and publish them later." },
      { heading: "Edit / Delete", detail: "Click the edit (pencil) icon on any announcement to modify it. Deleting removes it from the public site immediately." },
    ],
    tips: ["Set an expiry date for time-sensitive notices so they auto-hide after the event.", "Drafts let you prepare announcements in advance."],
  },
  {
    id: "calendar",
    title: "Events Calendar",
    icon: Calendar,
    roles: ["admin"],
    color: "from-cyan-500 to-cyan-700",
    overview:
      "The Events Calendar lets you manage all Gurukul events that appear on the public website's calendar page — festivals, special classes, exams, closures, and community gatherings.",
    steps: [
      { heading: "Add event", detail: "Click Add Event. Fill in the event name, date, time, location, and a short description. Save to publish it immediately." },
      { heading: "Edit / Delete", detail: "Click any event in the list to edit its details. Delete removes it from the public calendar." },
      { heading: "Public view", detail: "Events appear on the website in chronological order. Past events are shown below upcoming events." },
    ],
    tips: ["Add recurring events (e.g. monthly puja) individually since recurring events are not yet automated.", "Use the Description field to give parents all the details they need."],
  },
  {
    id: "messaging",
    title: "Communication Hub",
    icon: Mail,
    roles: ["admin"],
    color: "from-teal-500 to-teal-700",
    overview:
      "The Communication Hub enables the Admin to send email communications to parents and families. Use it for broadcast notices, fee reminders, or targeted messages to a specific course group.",
    steps: [
      { heading: "Compose message", detail: "Click Compose. Enter a subject and body. Use the recipient filter to choose All families, or target by course/level/section." },
      { heading: "Send", detail: "Click Send. Emails are dispatched immediately using the Gurukul's configured email address (SMTP)." },
      { heading: "View history", detail: "The Sent tab shows all previous messages with timestamps and recipient counts." },
    ],
    notes: ["SMTP must be configured in the server environment for emails to be delivered. Contact the system administrator if emails are not being received."],
    tips: ["Test by sending to yourself first.", "Use specific subject lines so parents don't mistake messages for spam."],
  },
  {
    id: "roles",
    title: "User Management",
    icon: ShieldCheck,
    roles: ["admin"],
    color: "from-red-500 to-red-700",
    overview:
      "User Management shows all portal accounts for teachers and assistants. Teacher and Assistant accounts are created automatically when you add staff in Staff Management — you do not create them manually here. Use this page to review account status, view role assignments, reset PINs, and add portal access for staff who are already in Staff Management.",
    steps: [
      { heading: "View all portal users", detail: "The list shows every portal account for teachers and assistants. Each row shows name, phone, role, and status." },
      { heading: "Add portal access", detail: "Click Add User. Search for an existing staff member (from Staff Management) by name. Select them and choose their role (Teacher or Assistant). A PIN is generated and shown once — copy it immediately." },
      { heading: "Reset PIN", detail: "Click the 🔑 Reset PIN button on any user row. A new PIN is generated and shown in a banner. The old PIN is immediately invalidated." },
      { heading: "Activate / Deactivate", detail: "Toggle a user's active status. Inactive users cannot log in but their account and history are preserved." },
      { heading: "Delete portal access", detail: "Click the trash icon to remove the portal login account. The staff member record in Staff Management is not affected." },
      { heading: "Role permissions reference", detail: "Click the 'Permissions' button to see a full comparison of what each role (Admin / Teacher / Assistant) can access." },
    ],
    notes: [
      "Teacher portal accounts are typically created automatically via Staff Management — only use this page to add portal access for staff added through other means.",
      "To reset a teacher's PIN, you can also use the 🔑 button here or in Staff Management — both work.",
      "PINs are bcrypt-hashed — nobody, including admins, can read them after creation.",
      "Admin (Super Admin) login uses email + password, not a PIN — admin accounts are not listed here.",
    ],
    tips: [
      "Deactivating an account immediately prevents login without deleting any records.",
      "Super Admin is the only account that uses email + password login; all other staff use phone + PIN.",
    ],
  },
  {
    id: "user-roles",
    title: "User Roles & Permissions",
    icon: KeyRound,
    roles: ["admin"],
    color: "from-violet-500 to-violet-700",
    overview:
      "The portal has five roles: Super Admin, Gurukul Admin, Course Coordinator, Operations Manager, Teacher, and Assistant. Each role sees only the modules they need. Super Admin and Gurukul Admin have full access. Course Coordinators focus on academic and communications modules. Operations Managers focus on student, member, and registration data. Teachers handle classroom-level operations including Weekly Updates and the Communication Hub. Assistants have a more limited scope: Courses & Classes, Attendance, and Course Documents only — they cannot send Weekly Updates or access the Communication Hub.",
    steps: [
      { heading: "Create an admin account", detail: "Go to User Management → click Add User. Enter the user's full name, US phone number (used as username), choose their role from the dropdown (Gurukul Admin / Course Coordinator / Operations Manager), and set a temporary 4-digit PIN. The PIN is shown once — copy and share it securely. The user logs in with their phone number + PIN." },
      { heading: "Edit an admin's role", detail: "Click Edit on any admin row. Change the Role dropdown and click Save Changes. The change takes effect on their next login. An audit log entry records the role change." },
      { heading: "Deactivate an account", detail: "Click Deactivate on the row. The user is immediately blocked from logging in. Their data and history are preserved. Click Activate to restore access." },
      { heading: "Reset a PIN", detail: "Click Reset PIN on any row. A new 4-digit PIN is generated and shown once. Share it with the user — the old PIN stops working immediately." },
      { heading: "Delete an account", detail: "Click the trash icon, then Confirm. The account is permanently removed. This cannot be undone. The staff member record (in Staff Management) is not affected." },
      { heading: "View the permissions matrix", detail: "Click the Permissions button at the top-right of User Management to see a full side-by-side comparison of all five roles and which modules each can access." },
    ],
    notes: [
      "Super Admin (admin@gurukul.org) logs in with email + password and cannot be deactivated, deleted, or have their role changed.",
      "Course Coordinators can access: Course Management, Staff Management, Inventory, Communication Hub, and Calendar.",
      "Operations Managers can access: Dashboard, Student Registration, Student Management, and Member Management.",
      "Neither Course Coordinators nor Operations Managers can access User Management, Audit Logs, or Settings — those remain Admin-only.",
      "Role changes are recorded in the Audit Log with the old and new role for accountability.",
      "A user whose account is deactivated is blocked instantly — no grace period.",
    ],
    tips: [
      "Use Course Coordinator for department heads or senior teachers who manage curricula but should not see financial or student data.",
      "Use Operations Manager for office staff who handle registrations and member records but do not need academic management access.",
      "Always reset the PIN immediately after creating an account so the user can set their own.",
      "The Permissions button gives a quick visual reference — bookmark it for onboarding new users.",
    ],
  },
  {
    id: "courses",
    title: "Courses & Classes",
    icon: BookOpen,
    roles: ["teacher", "assistant"],
    color: "from-blue-500 to-blue-700",
    overview:
      "Courses & Classes is the teacher's primary view. It shows all courses, levels, and sections with enrolled student rosters. Teachers see all courses; the student search lets you find any student across all courses instantly.",
    steps: [
      { heading: "Browse courses", detail: "Open Courses & Classes in the sidebar. Course cards are shown at the top — click a card to see its levels and student lists." },
      { heading: "Filter by year", detail: "Use the Curriculum Year filter to view classes for a specific academic year." },
      { heading: "View students", detail: "Click a section to see the enrolled student list — name, student code, enrollment status, and parent contact (M/F rows with phone and email). On mobile, parent contact appears inline below the student name." },
      { heading: "Search students", detail: "Click the Search box and start typing. It searches across all courses and sections simultaneously, showing student name, code, enrollment status, course/level, and parent contact." },
    ],
    tips: [
      "If you don't see a section you teach, ask the Admin to verify the enrollment in Student Management.",
      "The parent contact M/F rows let you call or email a student's parents directly from the student list.",
      "Student search is cross-course — useful for finding a student when you don't remember which class they're in.",
    ],
  },
  {
    id: "documents",
    title: "Course Documents",
    icon: FileText,
    roles: ["teacher", "assistant"],
    color: "from-purple-500 to-purple-700",
    overview:
      "Course Documents lets teachers upload and manage learning materials, worksheets, PDFs, reference links, and resources for their classes.",
    steps: [
      { heading: "Select class", detail: "Choose the course and section for the document." },
      { heading: "Upload", detail: "Click Upload Document. Enter a title and description. Either attach a file or paste a URL (Google Doc, YouTube link, etc.)." },
      { heading: "Manage", detail: "Edit or delete documents at any time. Documents are visible to enrolled students if the parent portal sharing is enabled." },
    ],
    tips: ["For large files, use a cloud link (Google Drive, Dropbox) rather than uploading directly.", "Name documents clearly so students and parents can identify them easily."],
  },
  {
    id: "attendance",
    title: "Attendance",
    icon: ClipboardList,
    roles: ["teacher", "assistant"],
    color: "from-green-500 to-green-700",
    overview:
      "Attendance lets teachers record who attended each class session. You can view historical records, see individual student attendance percentages, and generate summaries.",
    steps: [
      { heading: "Select class and date", detail: "Go to Attendance. Choose the course, level, and section. Pick the class date." },
      { heading: "Mark attendance", detail: "For each student, tap Present (✓) or Absent (✗). Add notes for tardiness or early departures if needed." },
      { heading: "Save", detail: "Click Save Attendance. Records are saved immediately." },
      { heading: "View history", detail: "Switch to the History tab to see past attendance records. Filter by date range or student." },
      { heading: "Attendance report", detail: "The report view shows each student's attendance percentage over a selected period — useful for identifying students who need follow-up." },
    ],
    tips: ["Mark attendance promptly after each class while it's fresh.", "Attendance is scoped to your assigned sections — you won't see other teachers' classes.", "Parents can be informed of absences through the Communication Hub (Admin only)."],
  },
  {
    id: "weekly-updates",
    title: "Messaging Center (Weekly Updates)",
    icon: Newspaper,
    roles: ["teacher", "assistant", "admin"],
    color: "from-amber-500 to-amber-700",
    overview:
      "The Messaging Center for teachers has two tabs: Weekly Updates (rich posts you publish each week for parents) and Announcements (school-wide notices from Admin — read-only for teachers). Weekly Updates are the primary way teachers communicate class progress to parents via the Parent Portal.",
    steps: [
      { heading: "Two tabs", detail: "'Weekly Updates' is where you create and manage your class update posts. 'Announcements' shows the latest school-wide notices published by the Admin — read-only for teachers." },
      { heading: "Create a new update", detail: "Click New Update. Use the cascading dropdowns to select Course → Level → Section." },
      { heading: "Set the week period and priority", detail: "Choose the Week Start and Week End dates. Set Priority — High (🔴 urgent, shown prominently on the Parent Portal), Normal, or Low." },
      { heading: "Enter a title", detail: "Write a descriptive title, e.g. 'Week 3 — Introduction to Devanagari Script'." },
      { heading: "Fill content sections", detail: "Class Highlights (required): summary of what happened. Topics Covered, Homework (highlighted in yellow on the Parent Portal), Upcoming Plan, Reminders (highlighted in rose) — optional but strongly recommended." },
      { heading: "Add an attachment", detail: "Paste a link to a Google Doc, YouTube video, or any resource parents should see." },
      { heading: "Save or Publish", detail: "Click Save Draft to save privately, or Publish to make it visible on the Parent Portal immediately. You can edit a published update anytime." },
    ],
    tips: [
      "High Priority updates show a 🔴 badge on the Parent Portal — reserve for truly urgent notices.",
      "Draft updates are only visible to you and admins — parents cannot see them.",
      "You can edit a published update anytime. Changes are reflected on the Parent Portal immediately.",
      "The Announcements tab is read-only — new announcements are created by Admin in the Announcements section.",
    ],
  },
  {
    id: "settings",
    title: "Settings",
    icon: Settings,
    roles: ["all"],
    color: "from-gray-500 to-gray-700",
    overview:
      "Settings lets each user manage their own credentials and lets Admins configure portal-wide options including audit log retention, curriculum year, and fee defaults. Settings are organised into tabs: Account, Portal (Admin only), and Audit (Admin only).",
    steps: [
      { heading: "Change Password (Admin)", detail: "Go to Settings → Account tab. Under Change Password, enter your current password, then the new password twice. Click Update Password." },
      { heading: "Change PIN (Teacher/Assistant)", detail: "Go to Settings → Account tab. Under Change PIN, enter your current PIN, then the new 4-digit PIN twice. Click Update PIN." },
      { heading: "Portal settings (Admin)", detail: "Go to Settings → Portal tab. Set the current Curriculum Year, default fee amounts, and other portal-wide defaults. Changes save immediately." },
      { heading: "Audit log retention (Admin)", detail: "Go to Settings → System tab. The Audit Log Retention field controls how many days of audit logs are kept before automatic deletion. Choose 7 Days (default) or 15 Days (max) using the preset buttons, or type a value between 1–15 and click Save." },
      { heading: "Manual audit purge (Admin)", detail: "On the Audit Log page (separate from Settings), there is a Purge Now button that immediately deletes all logs older than the configured retention period. Use this if you need to reclaim space before the next scheduled purge." },
    ],
    notes: [
      "Admins cannot change their own PIN from Settings — they use a password.",
      "Teachers cannot change their password from Settings — they use a PIN.",
      "Audit logs are automatically purged on a schedule: once at server startup, then every 6 hours. Manual purge is instant.",
      "The maximum audit retention is capped at 15 days server-side — entering a higher value is silently capped.",
      "If you forget your current credentials, ask the Admin to reset them from User Management.",
    ],
    tips: [
      "Use 7 days (default) for most cases; choose 15 days only if you need a longer audit trail.",
      "Export the Audit Log to CSV before purging if you need a permanent record.",
      "7 days is sufficient for routine monitoring; switch to 15 days during high-activity periods like annual enrolment.",
    ],
  },
  {
    id: "students-corner",
    title: "Student's Corner",
    icon: Sparkles,
    roles: ["all"],
    color: "from-yellow-500 to-orange-500",
    overview:
      "Student's Corner is a public, gamified learning hub on the website at /students-corner. Students can explore 8 courses across two categories — Indian Languages (Hindi, Sanskrit, Telugu, Gujarati, Tamil, Kannada) and Culture & Dharma (Dharma, Music) — through quizzes, memory games, fun facts, and more. No login is required.",
    steps: [
      { heading: "Access", detail: "Students (and anyone) visit the website and click 'Student's Corner' in the navigation. No login is required — it is fully public." },
      { heading: "Choose a course", detail: "The home screen shows two categories: Indian Languages and Culture & Dharma. Select any course to enter its learning hub." },
      { heading: "Explore learning activities", detail: "Each course has interactive activities: quizzes, matching games, fun facts, word searches, and flashcards. Activities are age-appropriate and aligned with the course content." },
      { heading: "Track progress", detail: "Progress (completed activities, scores) is saved in the browser's local storage — no account needed. Students earn badges and see their completion percentage per course." },
      { heading: "Narad Ji", detail: "Narad Ji (the chatbot) appears in Student's Corner with a student-friendly greeting. Students can ask Narad Ji about courses, activities, or anything Gurukul-related." },
    ],
    notes: [
      "Progress is stored locally in the student's browser — clearing browser data will reset progress.",
      "Student's Corner is fully public — no login, no registration required to access it.",
      "Content is designed for students enrolled in the Gurukul but is open to anyone interested.",
    ],
    tips: [
      "Share the /students-corner link directly with parents to encourage students to practise at home.",
      "Narad Ji shows a special student-friendly greeting on the Student's Corner page.",
    ],
  },
  {
    id: "parent-portal",
    title: "Parent Portal",
    icon: Globe,
    roles: ["all"],
    color: "from-orange-500 to-orange-700",
    overview:
      "The Parent Portal is the public-facing section of the Gurukul website at /parents. It gives enrolled families access to Weekly Class Updates after verifying their temple membership via phone number. No app download or account is needed — parents just visit the website.",
    steps: [
      { heading: "Parent accesses the portal", detail: "Parents visit the website and click 'Parents Portal' in the navigation. They see a general overview page with Gurukul information." },
      { heading: "Access Weekly Updates", detail: "Parents click the 'View Weekly Updates' button to enter the gated section." },
      { heading: "Solve captcha", detail: "A simple captcha puzzle prevents automated bot access." },
      { heading: "Phone verification", detail: "Parents enter the phone number registered with their temple membership. If the number matches a record, access is granted for that session." },
      { heading: "View updates", detail: "Parents see all Published weekly updates from teachers, filterable by course. Each card expands to show full details: class highlights, topics covered, homework (highlighted in yellow), upcoming plan, reminders (highlighted in rose), and any attachment links." },
    ],
    notes: [
      "Only Published updates are visible to parents — Drafts remain private to the portal.",
      "High Priority updates display a 🔴 badge so parents immediately spot urgent notices.",
      "Parents cannot log in to edit anything — the portal is completely read-only for families.",
      "Phone verification uses the temple membership database — parents must be registered members with the phone they enter.",
    ],
    tips: [
      "Publish updates regularly — consistent communication keeps parents engaged.",
      "Use the Communication Hub to notify parents when new weekly updates are posted.",
      "For the Student's Corner (gamified learning), share /students-corner — no phone verification needed.",
    ],
  },
];

// ─── Tech Specs component ─────────────────────────────────────────────────────

type TechBlock = { title: string; icon: React.ElementType; color: string; items: { label: string; value: string }[] };
type TechGroup = { id: string; heading: string; icon: React.ElementType; gradient: string; blocks: TechBlock[]; notes?: string[] };

const TECH_GROUPS: TechGroup[] = [
  {
    id: "architecture",
    heading: "System Architecture",
    icon: Network,
    gradient: "from-slate-600 to-slate-800",
    blocks: [
      {
        title: "Overall Design",
        icon: Cpu,
        color: "bg-slate-100 text-slate-700",
        items: [
          { label: "Pattern",       value: "3-Tier: Client → REST API → PostgreSQL" },
          { label: "Monorepo",      value: "pnpm workspaces — shared packages across artifacts" },
          { label: "Artifacts",     value: "gurukul (web UI)  ·  api-server (backend)  ·  lib/db (shared ORM)" },
          { label: "Routing",       value: "Path-based proxy — /gurukul prefix routes to Vite dev server; /api routes to Express" },
          { label: "Communication", value: "Frontend ↔ Backend via JSON REST (no GraphQL, no WebSockets)" },
          { label: "Runtime",       value: "Node.js 20 LTS — single process, pnpm workspace monorepo" },
        ],
      },
      {
        title: "Request Flow",
        icon: GitBranch,
        color: "bg-indigo-100 text-indigo-700",
        items: [
          { label: "1. Browser",    value: "React SPA served by Vite dev server on PORT env" },
          { label: "2. Auth check", value: "adminApi reads gurukul_admin_auth_v2 from localStorage; injects X-User-* headers" },
          { label: "3. API server", value: "Express 5 on port 8080 reads headers; applies RBAC middleware per route" },
          { label: "4. ORM",        value: "Drizzle ORM builds type-safe SQL → executes against PostgreSQL" },
          { label: "5. Response",   value: "JSON returned; frontend renders or shows toast on error" },
        ],
      },
    ],
    notes: [
      "There is no JWT or session cookie — identity is passed per-request as X-User-Email / X-User-Phone / X-User-Role / X-User-Name headers from localStorage.",
      "All API routes are protected server-side: Express middleware checks the role header against a RBAC table before proceeding.",
    ],
  },
  {
    id: "frontend",
    heading: "Frontend Stack",
    icon: Code2,
    gradient: "from-blue-500 to-blue-700",
    blocks: [
      {
        title: "Core Framework",
        icon: Code2,
        color: "bg-blue-100 text-blue-700",
        items: [
          { label: "Runtime",     value: "React 18 (functional components + hooks only)" },
          { label: "Build tool",  value: "Vite 7 — HMR in dev, ESBuild in prod" },
          { label: "Language",    value: "TypeScript (strict mode)" },
          { label: "Router",      value: "Wouter — lightweight client-side routing, no React-Router dependency" },
          { label: "State",       value: "useState / useEffect / useCallback / useMemo — no external state library" },
          { label: "Auth state",  value: "localStorage key gurukul_admin_auth_v2 (JSON); AuthContext provides user to all components" },
        ],
      },
      {
        title: "UI & Styling",
        icon: Wrench,
        color: "bg-sky-100 text-sky-700",
        items: [
          { label: "CSS",         value: "Tailwind CSS 3 — utility-first, no custom CSS files" },
          { label: "Components",  value: "shadcn/ui primitives (Button, Input, Label, Dialog, Select…)" },
          { label: "Icons",       value: "lucide-react — tree-shaken SVG icons" },
          { label: "Toasts",      value: "Sonner — non-blocking success / error notifications" },
          { label: "Charts",      value: "Recharts — used on Dashboard stats" },
          { label: "Fonts",       value: "Cinzel (headings) + Inter (body) loaded via Google Fonts" },
        ],
      },
      {
        title: "Key Conventions",
        icon: GitBranch,
        color: "bg-violet-100 text-violet-700",
        items: [
          { label: "API calls",   value: "All calls go through src/lib/adminApi.ts — a typed wrapper that injects auth headers" },
          { label: "Validation",  value: "src/lib/validators.ts — validatePersonName, validateEmail, validateUSPhone, formatUSPhone" },
          { label: "Path alias",  value: "@/ maps to src/ (configured in tsconfig + vite.config)" },
          { label: "Admin SPA",   value: "src/admin/AdminApp.tsx — wouter Switch defines all /admin/* routes" },
          { label: "Public SPA",  value: "src/App.tsx — public-facing pages (Home, Events, Parents, Students Corner)" },
        ],
      },
    ],
  },
  {
    id: "backend",
    heading: "Backend Stack",
    icon: Server,
    gradient: "from-emerald-500 to-emerald-700",
    blocks: [
      {
        title: "API Server",
        icon: Server,
        color: "bg-emerald-100 text-emerald-700",
        items: [
          { label: "Framework",   value: "Express 5 (beta) — async error handling built-in" },
          { label: "Runtime",     value: "Node.js 20 LTS, TypeScript compiled via esbuild (build.mjs)" },
          { label: "Port",        value: "Reads from PORT environment variable — no hard-coded port" },
          { label: "Logging",     value: "Pino logger — structured JSON logs with request ID, method, URL, status, responseTime" },
          { label: "Build",       value: "Bundled into dist/index.mjs by build.mjs before start; source maps included" },
          { label: "Dev mode",    value: "pnpm run build && pnpm run start on every restart (no ts-node or nodemon)" },
        ],
      },
      {
        title: "Route Structure",
        icon: Network,
        color: "bg-teal-100 text-teal-700",
        items: [
          { label: "/api/admin/auth",       value: "Login, logout, PIN verification, PIN reset" },
          { label: "/api/admin/members",    value: "CRUD + validate endpoint (PATCH /:id/validate)" },
          { label: "/api/admin/students",   value: "CRUD, bulk ops, enrollment management" },
          { label: "/api/admin/courses",    value: "Course / Level / Section CRUD + teacher assignment" },
          { label: "/api/admin/teachers",   value: "Staff CRUD + schedule builder" },
          { label: "/api/admin/attendance", value: "Mark, query, and export attendance per section/date" },
          { label: "/api/admin/audit",      value: "Query, export CSV, manual purge" },
          { label: "/api/admin/settings",   value: "Key-value portal settings store (portal_settings table)" },
          { label: "/api/public/*",         value: "Unauthenticated endpoints: events, announcements, weekly updates, parent verify" },
        ],
      },
      {
        title: "Background Jobs",
        icon: RefreshCw,
        color: "bg-green-100 text-green-700",
        items: [
          { label: "Audit purge",  value: "startAuditPurgeScheduler() — runs at boot then every 6 hours via setInterval" },
          { label: "Purge logic",  value: "Reads audit_retention_days from portal_settings; hard-caps at 90 days; deletes rows older than cutoff" },
          { label: "No cron",      value: "Pure Node.js setInterval — no OS cron, no external scheduler dependency" },
        ],
      },
    ],
    notes: [
      "The API server is stateless between requests — no in-memory session store. Identity comes entirely from request headers.",
      "Express 5 async errors bubble up automatically — no need for try/catch around async route handlers (though they are still used for explicit error messages).",
    ],
  },
  {
    id: "database",
    heading: "Database & Data Model",
    icon: Database,
    gradient: "from-violet-500 to-violet-700",
    blocks: [
      {
        title: "Database",
        icon: Database,
        color: "bg-violet-100 text-violet-700",
        items: [
          { label: "Engine",      value: "PostgreSQL 15 — connection via DATABASE_URL environment variable" },
          { label: "ORM",         value: "Drizzle ORM — type-safe schema, query builder, migrations" },
          { label: "Schema file", value: "lib/db/src/schema/gurukul.ts — single source of truth for all tables" },
          { label: "Migrations",  value: "drizzle-kit push (schema-push mode, no migration files)" },
          { label: "Connection",  value: "pg driver via node-postgres; connection pool managed by Drizzle" },
        ],
      },
      {
        title: "Core Tables & Relationships",
        icon: GitBranch,
        color: "bg-purple-100 text-purple-700",
        items: [
          { label: "members",            value: "Temple membership records — every student must FK → members.id" },
          { label: "gurukul_students",   value: "Student records (name, DOB, grade, contacts) → FK: member_id" },
          { label: "courses",            value: "Top-level course (Hindi, Dharma, Tamil…)" },
          { label: "course_levels",      value: "Level within a course (Beginner, Level 1…) → FK: course_id" },
          { label: "course_sections",    value: "Actual class batch (schedule, capacity) → FK: level_id" },
          { label: "enrollments",        value: "Student ↔ Section join table + payment fields → FKs: student_id, section_id" },
          { label: "teacher_users",      value: "Staff portal accounts (phone, bcrypt PIN hash, role, status)" },
          { label: "teacher_assignments",value: "Teacher ↔ Section join → FKs: teacher_id, section_id" },
          { label: "attendance_records", value: "Per-student per-session record → FKs: student_id, section_id, date" },
          { label: "weekly_updates",     value: "Teacher posts per section per week → FK: section_id, teacher_id" },
          { label: "audit_logs",         value: "Immutable event log — admin_name, module, action, entity, prev/new value, IP, timestamp" },
          { label: "portal_settings",    value: "Key-value settings store (audit_retention_days, fees, curriculum year…)" },
        ],
      },
      {
        title: "Key Constraints",
        icon: Shield,
        color: "bg-rose-100 text-rose-700",
        items: [
          { label: "member_id required",  value: "gurukul_students.member_id is NOT NULL — no orphan students" },
          { label: "Cascade deletes",     value: "Deleting a student cascades to enrollments and attendance; deleting a section cascades to assignments" },
          { label: "Unique phone",        value: "teacher_users.phone is UNIQUE — used as login identifier" },
          { label: "Audit immutable",     value: "audit_logs has no UPDATE endpoint — rows are insert-only, deleted only by the purge job" },
        ],
      },
    ],
  },
  {
    id: "auth",
    heading: "Authentication & Security",
    icon: Shield,
    gradient: "from-red-500 to-red-700",
    blocks: [
      {
        title: "Auth Mechanisms",
        icon: KeyRound,
        color: "bg-red-100 text-red-700",
        items: [
          { label: "Super Admin",   value: "Email + password (bcrypt hash, 12 rounds) stored in a dedicated admin_users table" },
          { label: "Teachers",      value: "Phone number + 4-digit PIN (bcrypt hash, 10 rounds) in teacher_users.pin_hash" },
          { label: "Session store", value: "No server-side session — auth object stored in localStorage after login and sent as request headers" },
          { label: "Headers used",  value: "X-User-Email, X-User-Phone, X-User-Role, X-User-Name — read by Express middleware" },
          { label: "Lockout",       value: "5 failed PIN attempts → account locked for 15 minutes (failed_attempts + locked_until columns)" },
          { label: "PIN visibility", value: "Plain PIN shown once in frontend banner after creation; never stored; hashed immediately at creation" },
        ],
      },
      {
        title: "RBAC (Role-Based Access Control)",
        icon: Shield,
        color: "bg-orange-100 text-orange-700",
        items: [
          { label: "Roles",         value: "super_admin · admin · teacher · assistant" },
          { label: "Enforcement",   value: "Server-side: requireRole() middleware checks X-User-Role header before handler runs" },
          { label: "Frontend",      value: "canAccess(role, module) helper in rbac.ts hides UI elements; never used as sole guard" },
          { label: "Admin only",    value: "Members, Students, Staff, Courses, Inventory, Settings, Audit, User Management" },
          { label: "Teacher+",      value: "Attendance, Course Documents, Weekly Updates (own sections only)" },
          { label: "All roles",     value: "Dashboard (read-only), Help & Guide, Settings (own PIN/password only)" },
        ],
      },
      {
        title: "Other Security Measures",
        icon: Shield,
        color: "bg-amber-100 text-amber-700",
        items: [
          { label: "CAPTCHA",        value: "Math equation CAPTCHA on public Parent Portal phone verification — prevents bot scraping" },
          { label: "Input sanitise", value: "All user inputs trimmed + validated (validators.ts) before DB insert" },
          { label: "Conflict check", value: "Teacher assignment endpoint returns HTTP 409 if time overlaps with existing assignment" },
          { label: "Audit trail",    value: "All Admin write actions logged to audit_logs with previous + new value, IP, timestamp" },
          { label: "HTTPS",          value: "TLS termination at the reverse proxy — all traffic to the app is encrypted in transit" },
        ],
      },
    ],
    notes: [
      "Because identity is in localStorage headers (not cookies), the portal is not vulnerable to CSRF. However, XSS could expose the stored token — ensure no untrusted content is rendered as raw HTML.",
      "PIN reset immediately invalidates the old hash — the teacher is effectively logged out on their next API call.",
    ],
  },
  {
    id: "audit-system",
    heading: "Audit Log System",
    icon: BarChart2,
    gradient: "from-teal-500 to-teal-700",
    blocks: [
      {
        title: "What Gets Logged",
        icon: ClipboardList,
        color: "bg-teal-100 text-teal-700",
        items: [
          { label: "Logged fields",   value: "admin_name, module_name, action_type, entity_name, entity_id, previous_value, new_value, ip_address, created_at" },
          { label: "Modules tracked", value: "Members, Students, Courses, Staff, Attendance, Settings, Auth, Announcements, Events, Inventory" },
          { label: "Actions tracked", value: "CREATE, UPDATE, DELETE, LOGIN, LOGOUT, PIN_RESET, VALIDATE, BULK_ACTION" },
          { label: "Who logs",        value: "Backend: logAudit() helper in lib/audit.ts — called inside each route handler after successful DB write" },
          { label: "Insert-only",     value: "Rows are never updated — only inserted (by logAudit) or deleted (by purge job)" },
        ],
      },
      {
        title: "Retention & Auto-Purge",
        icon: RefreshCw,
        color: "bg-cyan-100 text-cyan-700",
        items: [
          { label: "Default retention", value: "15 days" },
          { label: "Maximum retention", value: "90 days (enforced server-side with Math.min)" },
          { label: "Schedule",          value: "Runs at server boot + every 6 hours (setInterval)" },
          { label: "Purge query",       value: "DELETE FROM audit_logs WHERE created_at < NOW() − retention_days" },
          { label: "Setting source",    value: "portal_settings WHERE key = 'audit_retention_days' — editable from Settings → Audit tab" },
          { label: "Manual purge",      value: "POST /api/admin/audit/purge — available from Audit Log page" },
        ],
      },
    ],
    notes: [
      "Purged records are gone permanently — there is no recycle bin or archive. Export to CSV before purging if historical records are needed.",
      "The audit log itself is not audited — purges do not create an audit entry to avoid infinite recursion.",
    ],
  },
  {
    id: "deployment",
    heading: "Build, Deploy & Source Control",
    icon: GitBranch,
    gradient: "from-gray-600 to-gray-800",
    blocks: [
      {
        title: "Build Pipeline",
        icon: Cpu,
        color: "bg-gray-100 text-gray-700",
        items: [
          { label: "Frontend build",  value: "Vite 7 — ESBuild bundler; outputs static assets to dist/" },
          { label: "Backend build",   value: "esbuild via build.mjs — bundles TypeScript to dist/index.mjs with source maps" },
          { label: "Dev mode",        value: "Both servers run concurrently — Vite HMR for frontend, build+restart for backend" },
          { label: "Type checking",   value: "tsc --noEmit run at CI time; strict mode enabled across all packages" },
          { label: "Shared code",     value: "lib/db (schema + migrations) imported by both api-server and any future services" },
        ],
      },
      {
        title: "Runtime Configuration",
        icon: Wrench,
        color: "bg-slate-100 text-slate-700",
        items: [
          { label: "PORT",            value: "Read from environment — frontend dev server and Express both bind to PORT" },
          { label: "DATABASE_URL",    value: "PostgreSQL connection string — injected at runtime, never hard-coded" },
          { label: "NODE_ENV",        value: "development (local) / production (deployed) — gates cache headers and error verbosity" },
          { label: "GITHUB_PAT",      value: "Personal Access Token — used only for git push to the source repository" },
        ],
      },
      {
        title: "Source Control",
        icon: GitBranch,
        color: "bg-indigo-100 text-indigo-700",
        items: [
          { label: "Repository",      value: "GitHub — gurukulit-bht/gurukul-portal (private)" },
          { label: "Branch strategy", value: "Single master branch — all changes committed directly" },
          { label: "Schema changes",  value: "drizzle-kit push — schema-push mode applies schema diffs without migration files" },
          { label: "Prod schema",     value: "Run drizzle-kit push against the production DATABASE_URL to apply changes in prod" },
        ],
      },
    ],
    notes: [
      "Production and development databases are completely separate — schema changes in dev do not automatically propagate to prod.",
      "Environment variables are the only runtime configuration mechanism — no config files are read at startup.",
    ],
  },
];

function TechGroupBlock({ block }: { block: TechBlock }) {
  const Icon = block.icon;
  return (
    <div className="bg-white rounded-xl border border-border/70 overflow-hidden">
      <div className={`flex items-center gap-2 px-4 py-2.5 border-b border-border/50 ${block.color} bg-opacity-60`}>
        <Icon className="w-3.5 h-3.5 shrink-0" />
        <span className="text-xs font-bold uppercase tracking-wide">{block.title}</span>
      </div>
      <div className="divide-y divide-border/40">
        {block.items.map((item, i) => (
          <div key={i} className="flex gap-3 px-4 py-2 hover:bg-gray-50/60 transition-colors">
            <dt className="text-[11px] font-semibold text-muted-foreground whitespace-nowrap min-w-[130px] pt-0.5">{item.label}</dt>
            <dd className="text-[11px] text-secondary leading-relaxed font-mono">{item.value}</dd>
          </div>
        ))}
      </div>
    </div>
  );
}

function TechGroupCard({ group }: { group: TechGroup }) {
  const [open, setOpen] = useState(false);
  const Icon = group.icon;
  return (
    <div className="bg-white rounded-2xl border border-border shadow-sm overflow-hidden">
      <button
        className="w-full flex items-center gap-4 px-5 py-4 text-left hover:bg-gray-50 transition-colors"
        onClick={() => setOpen(v => !v)}
      >
        <div className={`w-9 h-9 rounded-xl bg-gradient-to-br ${group.gradient} flex items-center justify-center shrink-0`}>
          <Icon className="w-4 h-4 text-white" />
        </div>
        <div className="flex-1 min-w-0">
          <h3 className="font-bold text-secondary text-sm">{group.heading}</h3>
          {!open && (
            <p className="text-xs text-muted-foreground mt-0.5">
              {group.blocks.map(b => b.title).join("  ·  ")}
            </p>
          )}
        </div>
        <div className="shrink-0 text-muted-foreground">
          {open ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
        </div>
      </button>

      {open && (
        <div className="border-t border-border bg-gray-50/40 px-5 py-5 space-y-4">
          <div className="grid gap-4 sm:grid-cols-1 lg:grid-cols-2">
            {group.blocks.map((block, i) => (
              <TechGroupBlock key={i} block={block} />
            ))}
          </div>
          {group.notes && group.notes.length > 0 && (
            <div className="bg-blue-50 border border-blue-200 rounded-xl p-4">
              <h4 className="text-xs font-bold text-blue-800 uppercase tracking-wider mb-2">📌 Architecture Notes</h4>
              <ul className="space-y-1.5">
                {group.notes.map((n, i) => (
                  <li key={i} className="text-xs text-blue-900 flex gap-2">
                    <span className="shrink-0">•</span><span>{n}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function TechSpecs() {
  return (
    <div className="space-y-4">
      {/* Architecture diagram */}
      <div className="bg-slate-800 rounded-2xl p-5 font-mono text-xs leading-relaxed overflow-x-auto">
        <div className="text-slate-400 mb-3 font-sans text-[11px] font-semibold uppercase tracking-wider">System Architecture Overview</div>
        <pre className="text-slate-100 whitespace-pre">{`
  ┌─────────────────────────────────────────────────────────────┐
  │                    Browser (React SPA)                      │
  │   Vite · Wouter · Tailwind · shadcn/ui · lucide-react       │
  │   Auth: localStorage → X-User-* headers on every request   │
  └─────────────────────┬───────────────────────────────────────┘
                        │ HTTPS (TLS at reverse proxy)
  ┌─────────────────────▼───────────────────────────────────────┐
  │              Express 5 API Server (Node.js 20)              │
  │   Routes: /api/admin/*  ·  /api/public/*                    │
  │   Middleware: RBAC role check → Pino logger → route handler │
  │   Jobs: Audit purge (boot + every 6 h via setInterval)      │
  └──────────────┬──────────────────────┬───────────────────────┘
                 │ Drizzle ORM          │ logAudit()
  ┌──────────────▼──────────┐  ┌────────▼──────────────────────┐
  │     PostgreSQL 15        │  │       audit_logs table        │
  │  15 core tables          │  │  insert-only · purged ≤ 90 d  │
  └─────────────────────────┘  └───────────────────────────────┘
`.trim()}</pre>
      </div>

      {/* Stack quick-ref */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {[
          { icon: Code2,    label: "Frontend",  val: "React 18 + Vite 7",    color: "bg-blue-50 border-blue-200 text-blue-800"    },
          { icon: Server,   label: "Backend",   val: "Express 5 + Node 20",  color: "bg-emerald-50 border-emerald-200 text-emerald-800" },
          { icon: Database, label: "Database",  val: "PostgreSQL 15",        color: "bg-violet-50 border-violet-200 text-violet-800" },
          { icon: Shield,   label: "Auth",      val: "bcrypt + RBAC headers",color: "bg-rose-50 border-rose-200 text-rose-800"    },
        ].map(c => {
          const Icon = c.icon;
          return (
            <div key={c.label} className={`rounded-xl border p-3 text-center ${c.color}`}>
              <Icon className="w-5 h-5 mx-auto mb-1.5 opacity-80" />
              <div className="text-[11px] font-bold uppercase tracking-wide opacity-70 mb-0.5">{c.label}</div>
              <div className="text-[11px] font-semibold leading-tight">{c.val}</div>
            </div>
          );
        })}
      </div>

      {/* Detailed groups */}
      <div className="space-y-3">
        {TECH_GROUPS.map(g => <TechGroupCard key={g.id} group={g} />)}
      </div>
    </div>
  );
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function RolePill({ role }: { role: Role }) {
  const map: Record<Role, { label: string; cls: string }> = {
    admin:     { label: "Admin",     cls: "bg-red-100 text-red-700"    },
    teacher:   { label: "Teacher",   cls: "bg-blue-100 text-blue-700"  },
    assistant: { label: "Assistant", cls: "bg-purple-100 text-purple-700" },
    all:       { label: "All Roles", cls: "bg-green-100 text-green-700" },
  };
  const { label, cls } = map[role];
  return <span className={`text-[11px] font-semibold px-2 py-0.5 rounded-full ${cls}`}>{label}</span>;
}

function AccordionSection({ section, defaultOpen }: { section: SpecSection; defaultOpen?: boolean }) {
  const [open, setOpen] = useState(defaultOpen ?? false);
  const Icon = section.icon;
  return (
    <div className="bg-white rounded-2xl border border-border shadow-sm overflow-hidden">
      <button
        className="w-full flex items-center gap-4 px-5 py-4 text-left hover:bg-gray-50 transition-colors"
        onClick={() => setOpen(v => !v)}
      >
        <div className={`w-9 h-9 rounded-xl bg-gradient-to-br ${section.color} flex items-center justify-center shrink-0`}>
          <Icon className="w-4 h-4 text-white" />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-center gap-2">
            <h3 className="font-bold text-secondary text-sm">{section.title}</h3>
            {section.roles.map(r => <RolePill key={r} role={r} />)}
          </div>
          {!open && (
            <p className="text-xs text-muted-foreground mt-0.5 truncate">{section.overview.slice(0, 90)}…</p>
          )}
        </div>
        <div className="shrink-0 text-muted-foreground">
          {open ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
        </div>
      </button>

      {open && (
        <div className="border-t border-border px-5 py-5 space-y-5 bg-gray-50/40">
          <p className="text-sm text-muted-foreground leading-relaxed">{section.overview}</p>

          {section.steps && section.steps.length > 0 && (
            <div>
              <h4 className="text-xs font-bold text-secondary uppercase tracking-wider mb-3">How it works</h4>
              <ol className="space-y-3">
                {section.steps.map((s, i) => (
                  <li key={i} className="flex gap-3">
                    <div className={`w-6 h-6 rounded-full bg-gradient-to-br ${section.color} text-white text-xs font-bold flex items-center justify-center shrink-0 mt-0.5`}>
                      {i + 1}
                    </div>
                    <div>
                      <span className="text-sm font-semibold text-secondary">{s.heading} — </span>
                      <span className="text-sm text-muted-foreground">{s.detail}</span>
                    </div>
                  </li>
                ))}
              </ol>
            </div>
          )}

          {section.tips && section.tips.length > 0 && (
            <div className="bg-amber-50 border border-amber-200 rounded-xl p-4">
              <h4 className="text-xs font-bold text-amber-800 uppercase tracking-wider mb-2">💡 Tips</h4>
              <ul className="space-y-1.5">
                {section.tips.map((t, i) => (
                  <li key={i} className="text-xs text-amber-900 flex gap-2">
                    <span className="shrink-0">•</span>
                    <span>{t}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {section.notes && section.notes.length > 0 && (
            <div className="bg-blue-50 border border-blue-200 rounded-xl p-4">
              <h4 className="text-xs font-bold text-blue-800 uppercase tracking-wider mb-2">📌 Important Notes</h4>
              <ul className="space-y-1.5">
                {section.notes.map((n, i) => (
                  <li key={i} className="text-xs text-blue-900 flex gap-2">
                    <span className="shrink-0">•</span>
                    <span>{n}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ─── Main page ────────────────────────────────────────────────────────────────

export default function Help() {
  const { user } = useAuth();
  const [activeTab, setActiveTab]   = useState<"guide" | "techspecs">("guide");
  const [search, setSearch]         = useState("");
  const [roleFilter, setRoleFilter] = useState<"all" | "admin" | "teacher" | "assistant">("all");
  const [expandAll, setExpandAll]   = useState(false);

  const userRole = user?.role ?? "admin";

  function isVisible(s: SpecSection) {
    const roleMatch =
      roleFilter === "all"
        ? s.roles.includes("all") || s.roles.includes(userRole as Role) || s.roles.some(r => r === roleFilter)
        : s.roles.includes("all") || s.roles.includes(roleFilter as Role);
    const q = search.toLowerCase();
    const textMatch = !q ||
      s.title.toLowerCase().includes(q) ||
      s.overview.toLowerCase().includes(q) ||
      s.steps?.some(st => st.heading.toLowerCase().includes(q) || st.detail.toLowerCase().includes(q)) ||
      s.tips?.some(t => t.toLowerCase().includes(q));
    return roleMatch && textMatch;
  }

  const visible = SECTIONS.filter(isVisible);

  const ROLE_FILTER_OPTS = [
    { value: "all",       label: "All Roles" },
    { value: "admin",     label: "Admin only" },
    { value: "teacher",   label: "Teacher / Assistant" },
  ] as const;

  return (
    <div className="space-y-6 max-w-4xl mx-auto">

      {/* ── Hero ──────────────────────────────────────────────────────── */}
      <div className="rounded-2xl overflow-hidden shadow-sm"
        style={{ background: "linear-gradient(135deg, #92400e 0%, #d97706 60%, #fbbf24 100%)" }}>
        <div className="px-6 py-8 flex gap-5 items-center">
          <div className="w-16 h-16 rounded-2xl bg-white/20 flex items-center justify-center text-4xl shrink-0 select-none">
            {activeTab === "guide" ? "🪗" : "⚙️"}
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white mb-1">
              {activeTab === "guide" ? "Help & Functional Guide" : "Technical Specifications"}
            </h1>
            <p className="text-amber-100 text-sm max-w-lg leading-relaxed">
              {activeTab === "guide"
                ? "Everything you need to know about every feature — written clearly, step by step. Use the search or role filter to find what you need."
                : "Architectural details, technology stack, data model, security model, and infrastructure reference for the Gurukul Admin Portal."}
            </p>
          </div>
        </div>

        {/* Tab switcher */}
        <div className="px-6 pb-5 flex gap-2">
          {([
            { id: "guide",     label: "Functional Guide",   icon: "📖" },
            { id: "techspecs", label: "Technical Specs",    icon: "⚙️" },
          ] as const).map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-semibold transition-all ${
                activeTab === tab.id
                  ? "bg-white text-amber-800 shadow-sm"
                  : "bg-white/20 text-white hover:bg-white/30"
              }`}
            >
              <span>{tab.icon}</span> {tab.label}
            </button>
          ))}
        </div>
      </div>

      {/* ── TECHNICAL SPECS TAB ───────────────────────────────────────── */}
      {activeTab === "techspecs" && <TechSpecs />}

      {/* ── FUNCTIONAL GUIDE TAB ─────────────────────────────────────── */}
      {activeTab === "guide" && (
        <>
          {/* Filters */}
          <div className="bg-white rounded-2xl border border-border shadow-sm px-5 py-4 flex flex-wrap gap-3 items-center">
            <div className="relative flex-1 min-w-[180px]">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <input
                className="w-full pl-9 pr-4 py-2 text-sm border border-border rounded-xl focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary"
                placeholder="Search features…"
                value={search}
                onChange={e => setSearch(e.target.value)}
              />
            </div>
            <div className="flex gap-1.5">
              {ROLE_FILTER_OPTS.map(opt => (
                <button
                  key={opt.value}
                  onClick={() => setRoleFilter(opt.value)}
                  className={`px-3 py-1.5 rounded-xl text-xs font-semibold border transition-all ${
                    roleFilter === opt.value
                      ? "bg-secondary text-white border-secondary"
                      : "border-border text-muted-foreground hover:border-secondary/50 hover:text-secondary"
                  }`}
                >
                  {opt.label}
                </button>
              ))}
            </div>
            <button
              onClick={() => setExpandAll(v => !v)}
              className="ml-auto text-xs text-primary underline underline-offset-2 hover:text-primary/80 transition-colors whitespace-nowrap"
            >
              {expandAll ? "Collapse all" : "Expand all"}
            </button>
            <span className="text-xs text-muted-foreground">
              {visible.length} of {SECTIONS.length} sections
            </span>
          </div>

          {/* Sections */}
          {visible.length === 0 ? (
            <div className="text-center py-16 text-muted-foreground">
              <HelpCircle className="w-12 h-12 mx-auto mb-3 opacity-30" />
              <p className="font-medium">No sections match your search</p>
              <p className="text-sm mt-1">Try different keywords or clear the filter.</p>
            </div>
          ) : (
            <div className="space-y-3">
              {visible.map(s => (
                <AccordionSection key={s.id} section={s} defaultOpen={expandAll} />
              ))}
            </div>
          )}

          {/* Footer */}
          <div className="bg-amber-50 border border-amber-200 rounded-2xl px-5 py-4 text-sm text-amber-800 text-center">
            🙏 <strong>Narayan Narayan!</strong> Still have questions? Click the <strong>🪗</strong> button at the bottom-right of any page to chat with Narad Ji directly.
          </div>
        </>
      )}
    </div>
  );
}
