import { Router, type IRouter, type Request, type Response, type NextFunction } from "express";
import bcrypt from "bcryptjs";
import { db } from "@workspace/db";
import { adminUsersTable, coursesTable, teachersTable } from "@workspace/db/schema";
import { eq, isNotNull, sql, inArray } from "drizzle-orm";
import { writeAudit } from "../../lib/audit";

const router: IRouter = Router();

const SUPER_ADMIN_EMAIL  = "admin@gurukul.org";
const SUPER_ADMIN_ROLE   = "super_admin";
const SUPER_ADMIN_OVERRIDE_PIN = "6148229213";

const ALLOWED_ADMIN_ROLES = ["admin", "course_coordinator", "operations_manager"] as const;
type AssignableRole = typeof ALLOWED_ADMIN_ROLES[number];

// ── Backend role guard ────────────────────────────────────────────────────────
function requireAdminRole(req: Request, res: Response, next: NextFunction) {
  const role = req.headers["x-user-role"] as string | undefined;
  if (role !== "admin") {
    return res.status(403).json({ error: "Access denied. Admin privilege required." });
  }
  next();
}

function safeAdmin(
  u: typeof adminUsersTable.$inferSelect,
  creatorName?: string | null,
  updaterName?: string | null,
  assignedCourseName?: string | null,
) {
  return {
    id:                 u.id,
    name:               u.name,
    email:              u.email ?? null,
    phone:              u.phone ?? null,
    role:               u.role,
    status:             u.status,
    assignedCourseId:   u.assignedCourseId ?? null,
    assignedCourseName: assignedCourseName ?? null,
    linkedTeacherId:    u.linkedTeacherId ?? null,
    createdById:        u.createdById ?? null,
    createdBy:          creatorName ?? null,
    updatedById:        u.updatedById ?? null,
    updatedBy:          updaterName ?? null,
    lastLoginAt:        u.lastLoginAt ?? null,
    createdAt:          u.createdAt,
    updatedAt:          u.updatedAt,
  };
}

async function getEnrichedList() {
  const rows = await db.select().from(adminUsersTable).orderBy(adminUsersTable.createdAt);
  const nameById = new Map(rows.map((r) => [r.id, r.name]));

  // Build course name map for coordinator rows
  const courseIds = rows
    .map((r) => r.assignedCourseId)
    .filter((id): id is number => id != null);
  const courseNameMap = new Map<number, string>();
  if (courseIds.length > 0) {
    const courseRows = await db
      .select({ id: coursesTable.id, name: coursesTable.name })
      .from(coursesTable)
      .where(inArray(coursesTable.id, courseIds));
    courseRows.forEach((c) => courseNameMap.set(c.id, c.name));
  }

  return rows.map((r) =>
    safeAdmin(
      r,
      r.createdById ? nameById.get(r.createdById) ?? null : null,
      r.updatedById ? nameById.get(r.updatedById) ?? null : null,
      r.assignedCourseId ? (courseNameMap.get(r.assignedCourseId) ?? null) : null,
    )
  );
}

// ── Auto-create teacher record for coordinator ────────────────────────────────
// Creates a teacher row in the teachers table for a coordinator (no portal_users
// entry — coordinator uses admin portal login only).
// Returns { id, wasExisting } so callers can surface a notice when linking to
// an existing record rather than creating a new one.
async function ensureCoordinatorTeacher(
  name: string,
  email: string,
  phone: string,
  curriculumYear?: string,
): Promise<{ id: number; wasExisting: boolean }> {
  const cleanPhone = phone.replace(/\D/g, "");

  // Check if teacher with this email already exists — link rather than duplicate
  const [existing] = await db
    .select({ id: teachersTable.id })
    .from(teachersTable)
    .where(eq(teachersTable.email, email.trim()))
    .limit(1);

  if (existing) {
    // Update curriculum year on the existing record if provided
    if (curriculumYear?.trim()) {
      await db
        .update(teachersTable)
        .set({ curriculumYear: curriculumYear.trim() })
        .where(eq(teachersTable.id, existing.id));
    }
    return { id: existing.id, wasExisting: true };
  }

  const [created] = await db
    .insert(teachersTable)
    .values({
      name:           name.trim(),
      email:          email.trim(),
      phone:          cleanPhone,
      category:       "Teacher",
      status:         "Active",
      curriculumYear: curriculumYear?.trim() || null,
    })
    .returning({ id: teachersTable.id });

  return { id: created.id, wasExisting: false };
}

// GET /api/admin/admin-users
router.get("/", async (_req, res) => {
  try {
    res.json(await getEnrichedList());
  } catch (err) {
    res.status(500).json({ error: "Failed to fetch admin users." });
  }
});

// POST /api/admin/admin-users
// Body: { name, phone, email?, role?, assignedCourseId?, createdById }
// PIN is always auto-generated by the server and returned in the response.
router.post("/", requireAdminRole, async (req, res) => {
  try {
    const { name, phone, email, role, assignedCourseId, curriculumYear, createdById } = req.body as {
      name?: string; phone?: string; email?: string; role?: string;
      assignedCourseId?: number | null; curriculumYear?: string; createdById?: number;
    };

    if (!name?.trim())  return res.status(400).json({ error: "Name is required." });
    if (!phone?.trim()) return res.status(400).json({ error: "Phone number is required." });

    const cleanPhone = phone.replace(/\D/g, "");
    if (cleanPhone.length !== 10) return res.status(400).json({ error: "Phone must be exactly 10 digits." });

    // Always auto-generate a secure 4-digit PIN — never accept one from the client
    const pin = String(Math.floor(1000 + Math.random() * 9000));

    const assignedRole: AssignableRole = (ALLOWED_ADMIN_ROLES as readonly string[]).includes(role ?? "")
      ? (role as AssignableRole)
      : "admin";

    if (assignedRole === "course_coordinator" && !assignedCourseId) {
      return res.status(400).json({ error: "Course Coordinators must be assigned to a course." });
    }

    if (assignedRole === "course_coordinator" && !email?.trim()) {
      return res.status(400).json({ error: "Email is required for Course Coordinators." });
    }

    // Uniqueness check
    const [existing] = await db
      .select({ id: adminUsersTable.id })
      .from(adminUsersTable)
      .where(eq(adminUsersTable.phone, cleanPhone))
      .limit(1);
    if (existing) return res.status(409).json({ error: "An admin with this phone number already exists." });

    const pinHash = await bcrypt.hash(pin, 10);
    const [created] = await db
      .insert(adminUsersTable)
      .values({
        name:             name.trim(),
        email:            email?.trim() || null,
        phone:            cleanPhone,
        pinHash,
        role:             assignedRole,
        status:           "active",
        assignedCourseId: assignedRole === "course_coordinator" ? (assignedCourseId ?? null) : null,
        createdById:      createdById ?? null,
        updatedById:      createdById ?? null,
      })
      .returning();

    // Auto-create (or link) teacher record for coordinator — fail-fast: roll back if it fails
    let linkedExistingTeacher = false;
    if (assignedRole === "course_coordinator" && email?.trim()) {
      let teacherResult: { id: number; wasExisting: boolean };
      try {
        teacherResult = await ensureCoordinatorTeacher(name, email, cleanPhone, curriculumYear);
      } catch (teacherErr) {
        // Roll back the coordinator account that was just inserted
        await db.delete(adminUsersTable).where(eq(adminUsersTable.id, created.id));
        console.error("[admin-users POST] Failed to create/link teacher record — coordinator rolled back:", teacherErr);
        return res.status(500).json({ error: "Failed to create linked staff record. Coordinator account was not saved." });
      }
      await db
        .update(adminUsersTable)
        .set({ linkedTeacherId: teacherResult.id })
        .where(eq(adminUsersTable.id, created.id));
      linkedExistingTeacher = teacherResult.wasExisting;
    }

    const list = await getEnrichedList();
    await writeAudit(req, {
      moduleName: "User Management",
      actionType: "Add",
      entityName: name.trim(),
      entityId:   created.id,
      newValue:   { name: name.trim(), phone: cleanPhone, role: assignedRole, assignedCourseId: created.assignedCourseId ?? null },
    });
    res.status(201).json({ admin: list.find((a) => a.id === created.id), pin, linkedExistingTeacher });
  } catch (err) {
    console.error("[admin-users POST]", err);
    res.status(500).json({ error: "Failed to create admin user." });
  }
});

// PUT /api/admin/admin-users/:id
// Body: { name, phone, email?, status, role?, assignedCourseId?, updatedById }
router.put("/:id", requireAdminRole, async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    const { name, phone, email, status, role, assignedCourseId, updatedById } = req.body as {
      name?: string; phone?: string; email?: string; status?: string; role?: string;
      assignedCourseId?: number | null; updatedById?: number;
    };

    const [target] = await db.select().from(adminUsersTable).where(eq(adminUsersTable.id, id)).limit(1);
    if (!target) return res.status(404).json({ error: "Admin user not found." });

    if (!name?.trim()) return res.status(400).json({ error: "Name is required." });

    // Determine the effective role (after update)
    const effectiveRole = (role && target.role !== SUPER_ADMIN_ROLE && (ALLOWED_ADMIN_ROLES as readonly string[]).includes(role))
      ? (role as AssignableRole)
      : target.role;

    if (effectiveRole === "course_coordinator" && !assignedCourseId) {
      return res.status(400).json({ error: "Course Coordinators must be assigned to a course." });
    }

    if (effectiveRole === "course_coordinator" && !email?.trim()) {
      return res.status(400).json({ error: "Email is required for Course Coordinators." });
    }

    const updates: Partial<typeof adminUsersTable.$inferInsert> = {
      name:             name.trim(),
      status:           status ?? target.status,
      assignedCourseId: effectiveRole === "course_coordinator" ? (assignedCourseId ?? null) : null,
      updatedById:      updatedById ?? null,
      updatedAt:        new Date(),
    };

    // Store email for coordinator
    if (effectiveRole === "course_coordinator" && email?.trim()) {
      updates.email = email.trim();
    }

    // Allow role change for non-super-admin
    if (role && target.role !== SUPER_ADMIN_ROLE) {
      if (!(ALLOWED_ADMIN_ROLES as readonly string[]).includes(role)) {
        return res.status(400).json({ error: "Invalid role." });
      }
      updates.role = role as AssignableRole;
    }

    // Phone update only for non-super admins
    let newCleanPhone: string | undefined;
    if (target.role !== SUPER_ADMIN_ROLE && phone) {
      const cleanPhone = phone.replace(/\D/g, "");
      if (cleanPhone.length !== 10) return res.status(400).json({ error: "Phone must be exactly 10 digits." });
      const [dup] = await db
        .select({ id: adminUsersTable.id })
        .from(adminUsersTable)
        .where(sql`${adminUsersTable.phone} = ${cleanPhone} AND ${adminUsersTable.id} != ${id}`)
        .limit(1);
      if (dup) return res.status(409).json({ error: "Phone number already in use by another admin." });
      updates.phone = cleanPhone;
      newCleanPhone = cleanPhone;
    }

    const previousRole = target.role;
    await db.update(adminUsersTable).set(updates).where(eq(adminUsersTable.id, id));

    // Sync linked teacher record if coordinator
    if (target.linkedTeacherId) {
      const teacherSync: Partial<typeof teachersTable.$inferInsert> = { name: name.trim() };
      if (email?.trim()) teacherSync.email = email.trim();
      if (newCleanPhone) teacherSync.phone = newCleanPhone;
      const { curriculumYear: cyUpdate } = req.body as { curriculumYear?: string };
      if (cyUpdate?.trim()) teacherSync.curriculumYear = cyUpdate.trim();
      try {
        await db
          .update(teachersTable)
          .set(teacherSync)
          .where(eq(teachersTable.id, target.linkedTeacherId));
      } catch (teacherErr) {
        console.error("[admin-users PUT] Failed to sync teacher record:", teacherErr);
      }
    }

    // If role changed to coordinator and no teacher record yet, auto-create one
    if (
      updates.role === "course_coordinator" &&
      !target.linkedTeacherId &&
      (email?.trim() || target.email)
    ) {
      const teacherEmail = email?.trim() || target.email!;
      const teacherPhone = newCleanPhone || target.phone || "";
      try {
        const { curriculumYear: cyNew } = req.body as { curriculumYear?: string };
        const teacherResult = await ensureCoordinatorTeacher(name.trim(), teacherEmail, teacherPhone, cyNew);
        await db
          .update(adminUsersTable)
          .set({ linkedTeacherId: teacherResult.id })
          .where(eq(adminUsersTable.id, id));
      } catch (teacherErr) {
        console.error("[admin-users PUT] Failed to auto-create teacher on role change:", teacherErr);
      }
    }

    const list = await getEnrichedList();

    const auditNewValue: Record<string, unknown> = {
      name:   name.trim(),
      status: status ?? target.status,
    };
    if (updates.role && updates.role !== previousRole) {
      auditNewValue.roleChanged = { from: previousRole, to: updates.role };
    }
    if (updates.assignedCourseId !== undefined) {
      auditNewValue.assignedCourseId = updates.assignedCourseId;
    }

    await writeAudit(req, {
      moduleName: "User Management",
      actionType: "Edit",
      entityName: name.trim(),
      entityId:   id,
      newValue:   auditNewValue,
    });
    res.json(list.find((a) => a.id === id));
  } catch (err) {
    console.error("[admin-users PUT]", err);
    res.status(500).json({ error: "Failed to update admin user." });
  }
});

// PATCH /api/admin/admin-users/:id/reset-pin
router.patch("/:id/reset-pin", requireAdminRole, async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    const { updatedById } = req.body as { updatedById?: number };

    const [target] = await db.select().from(adminUsersTable).where(eq(adminUsersTable.id, id)).limit(1);
    if (!target) return res.status(404).json({ error: "Admin user not found." });
    if (target.role === SUPER_ADMIN_ROLE) return res.status(403).json({ error: "Cannot reset super admin PIN this way." });

    const newPin  = String(Math.floor(1000 + Math.random() * 9000));
    const pinHash = await bcrypt.hash(newPin, 10);
    await db.update(adminUsersTable).set({ pinHash, updatedById: updatedById ?? null, updatedAt: new Date() }).where(eq(adminUsersTable.id, id));
    await writeAudit(req, {
      moduleName: "User Management",
      actionType: "Edit",
      entityName: target.name,
      entityId:   id,
      newValue:   { action: "PIN Reset" },
    });
    res.json({ pin: newPin });
  } catch (err) {
    console.error("[admin-users reset-pin]", err);
    res.status(500).json({ error: "Failed to reset PIN." });
  }
});

// PATCH /api/admin/admin-users/:id/status
router.patch("/:id/status", requireAdminRole, async (req, res) => {
  try {
    const id     = parseInt(req.params.id);
    const { status, updatedById } = req.body as { status?: string; updatedById?: number };

    const [target] = await db.select().from(adminUsersTable).where(eq(adminUsersTable.id, id)).limit(1);
    if (!target) return res.status(404).json({ error: "Admin user not found." });
    if (target.role === SUPER_ADMIN_ROLE) return res.status(403).json({ error: "Super admin cannot be deactivated." });
    if (status !== "active" && status !== "inactive") return res.status(400).json({ error: "Invalid status." });

    await db.update(adminUsersTable).set({ status, updatedById: updatedById ?? null, updatedAt: new Date() }).where(eq(adminUsersTable.id, id));

    // Mirror status to linked teacher record
    if (target.linkedTeacherId) {
      const teacherStatus = status === "active" ? "Active" : "Inactive";
      try {
        await db
          .update(teachersTable)
          .set({ status: teacherStatus as "Active" | "Inactive" })
          .where(eq(teachersTable.id, target.linkedTeacherId));
      } catch (teacherErr) {
        console.error("[admin-users status] Failed to mirror status to teacher:", teacherErr);
      }
    }

    await writeAudit(req, {
      moduleName: "User Management",
      actionType: "Edit",
      entityName: target.name,
      entityId:   id,
      newValue:   { status },
    });
    res.json({ success: true, status });
  } catch (err) {
    res.status(500).json({ error: "Failed to update status." });
  }
});

// DELETE /api/admin/admin-users/:id
router.delete("/:id", requireAdminRole, async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    const [target] = await db.select().from(adminUsersTable).where(eq(adminUsersTable.id, id)).limit(1);
    if (!target) return res.status(404).json({ error: "Admin user not found." });
    if (target.role === SUPER_ADMIN_ROLE) return res.status(403).json({ error: "Super admin cannot be deleted." });

    // Delete linked teacher record first (cascade cleans up section/course assignments).
    // Fail-fast: if teacher deletion fails, do not delete the coordinator account either.
    if (target.linkedTeacherId) {
      await db.delete(teachersTable).where(eq(teachersTable.id, target.linkedTeacherId));
    }

    await db.delete(adminUsersTable).where(eq(adminUsersTable.id, id));
    await writeAudit(req, {
      moduleName: "User Management",
      actionType: "Delete",
      entityName: target.name,
      entityId:   id,
      previousValue: { name: target.name, role: target.role },
    });
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: "Failed to delete admin user." });
  }
});

// POST /api/admin/admin-users/super-admin/change-password
router.post("/super-admin/change-password", async (req, res) => {
  try {
    const { overridePin, newPassword } = req.body as { overridePin?: string; newPassword?: string };

    if (!overridePin || !newPassword) {
      return res.status(400).json({ error: "overridePin and newPassword are required." });
    }
    if (overridePin !== SUPER_ADMIN_OVERRIDE_PIN) {
      return res.status(403).json({ error: "Invalid override PIN. Please contact the system administrator." });
    }
    if (newPassword.length < 8) {
      return res.status(400).json({ error: "Password must be at least 8 characters." });
    }

    const [superAdmin] = await db
      .select()
      .from(adminUsersTable)
      .where(eq(adminUsersTable.role, SUPER_ADMIN_ROLE))
      .limit(1);
    if (!superAdmin) return res.status(404).json({ error: "Super admin account not found." });

    const newHash = await bcrypt.hash(newPassword, 10);
    await db.update(adminUsersTable).set({ pinHash: newHash, pinChanged: true, updatedAt: new Date() }).where(eq(adminUsersTable.id, superAdmin.id));
    res.json({ success: true });
  } catch (err) {
    console.error("[super-admin/change-password]", err);
    res.status(500).json({ error: "Failed to change password." });
  }
});

export { SUPER_ADMIN_EMAIL, SUPER_ADMIN_ROLE };
export default router;
